import java.util.Calendar;

/** GUI made in NetBeans IDE 8.2
  *
  * @author Aguirre, Gonzalo Adolfo
  */
public class GUI extends javax.swing.JFrame {
    private Biblioteca biblioteca;
    
  /**
    * Creates new form GUI
    */
  public GUI(Biblioteca pBiblioteca) {
    initComponents();
    
    this.biblioteca = pBiblioteca;
    
    this.setAllJPanelInvisible();
    jPanel_Intro.setVisible(true);
    jLabel18.setText(jLabel18.getText() + pBiblioteca.getNombre());
    this.setLocationRelativeTo(null);
  }

  /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel_Menu = new javax.swing.JPanel();
    buttonMenuLibros = new javax.swing.JButton();
    buttonMenuSocios = new javax.swing.JButton();
    buttonMenuPrestamos = new javax.swing.JButton();
    jLayeredPane1 = new javax.swing.JLayeredPane();
    jPanel_Intro = new javax.swing.JPanel();
    jLabel18 = new javax.swing.JLabel();
    jPanel_Libros = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    buttonLibrosAgregar = new javax.swing.JButton();
    buttonLibrosQuitar = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jPanel_LibrosAgregar = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    buttonLibrosFormularioAgregar = new javax.swing.JButton();
    jPanel_LibrosQuitar = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    buttonLibrosFormularioQuitar = new javax.swing.JButton();
    jComboBox2 = new javax.swing.JComboBox<>();
    jPanel_Socios = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    buttonSociosAgregar = new javax.swing.JButton();
    buttonSociosQuitar = new javax.swing.JButton();
    buttonSociosDocentesResponsables = new javax.swing.JButton();
    jTextField5 = new javax.swing.JTextField();
    buttonSociosBuscar = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jPanel_SociosAgregar = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jTextField9 = new javax.swing.JTextField();
    buttonSociosFormularioAgregar = new javax.swing.JButton();
    jComboBox1 = new javax.swing.JComboBox<>();
    jPanel_SociosQuitar = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    buttonSociosFormularioQuitar = new javax.swing.JButton();
    jComboBox3 = new javax.swing.JComboBox<>();
    jPanel_Prestamos = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    buttonPrestamosRealizar = new javax.swing.JButton();
    buttonPrestamosBuscar = new javax.swing.JButton();
    jComboBox4 = new javax.swing.JComboBox<>();
    buttonPrestamosCancelar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea3 = new javax.swing.JTextArea();
    jPanel_PrestamosPrestar = new javax.swing.JPanel();
    jLabel16 = new javax.swing.JLabel();
    jComboBox5 = new javax.swing.JComboBox<>();
    jComboBox6 = new javax.swing.JComboBox<>();
    buttonPrestamosFormularioRealizar = new javax.swing.JButton();
    jPanel_PrestamosDevolver = new javax.swing.JPanel();
    jLabel17 = new javax.swing.JLabel();
    jComboBox7 = new javax.swing.JComboBox<>();
    buttonPrestamosFormularioCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("poo-biblioteca-rev");
    setBackground(new java.awt.Color(142, 172, 187));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setMaximumSize(new java.awt.Dimension(600, 400));
    setResizable(false);
    setSize(new java.awt.Dimension(600, 400));

    jPanel_Menu.setBackground(new java.awt.Color(96, 125, 139));
    jPanel_Menu.setPreferredSize(new java.awt.Dimension(200, 400));

    buttonMenuLibros.setFont(new java.awt.Font("Leelawadee UI", 0, 30)); // NOI18N
    buttonMenuLibros.setText("Libros");
    buttonMenuLibros.setPreferredSize(new java.awt.Dimension(180, 75));
    buttonMenuLibros.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonMenuLibrosmouseReleased(evt);
      }
    });

    buttonMenuSocios.setFont(new java.awt.Font("Leelawadee UI", 0, 30)); // NOI18N
    buttonMenuSocios.setText("Socios");
    buttonMenuSocios.setPreferredSize(new java.awt.Dimension(180, 75));
    buttonMenuSocios.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonMenuSociosmouseReleased(evt);
      }
    });

    buttonMenuPrestamos.setFont(new java.awt.Font("Leelawadee UI", 0, 30)); // NOI18N
    buttonMenuPrestamos.setText("Prestamos");
    buttonMenuPrestamos.setPreferredSize(new java.awt.Dimension(180, 75));
    buttonMenuPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonMenuPrestamosmouseReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
    jPanel_Menu.setLayout(jPanel_MenuLayout);
    jPanel_MenuLayout.setHorizontalGroup(
      jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_MenuLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(buttonMenuLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonMenuSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonMenuPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel_MenuLayout.setVerticalGroup(
      jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_MenuLayout.createSequentialGroup()
        .addContainerGap(110, Short.MAX_VALUE)
        .addComponent(buttonMenuLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(buttonMenuSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(buttonMenuPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addGap(10, 10, 10))
    );

    jLayeredPane1.setPreferredSize(new java.awt.Dimension(400, 400));

    jPanel_Intro.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_Intro.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel18.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel18.setText("Bienvenido a ");

    javax.swing.GroupLayout jPanel_IntroLayout = new javax.swing.GroupLayout(jPanel_Intro);
    jPanel_Intro.setLayout(jPanel_IntroLayout);
    jPanel_IntroLayout.setHorizontalGroup(
      jPanel_IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_IntroLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel18)
        .addContainerGap(244, Short.MAX_VALUE))
    );
    jPanel_IntroLayout.setVerticalGroup(
      jPanel_IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_IntroLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel18)
        .addContainerGap(357, Short.MAX_VALUE))
    );

    jPanel_Libros.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_Libros.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel5.setText("Libros");

    buttonLibrosAgregar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonLibrosAgregar.setText("Agregar");
    buttonLibrosAgregar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonLibrosAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonLibrosAgregarmouseReleased(evt);
      }
    });

    buttonLibrosQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonLibrosQuitar.setText("Quitar");
    buttonLibrosQuitar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonLibrosQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonLibrosQuitarmouseReleased(evt);
      }
    });

    jTextArea1.setEditable(false);
    jTextArea1.setBackground(new java.awt.Color(96, 125, 139));
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextArea1.setRows(5);
    jTextArea1.setSelectionColor(new java.awt.Color(52, 81, 94));
    jScrollPane4.setViewportView(jTextArea1);

    javax.swing.GroupLayout jPanel_LibrosLayout = new javax.swing.GroupLayout(jPanel_Libros);
    jPanel_Libros.setLayout(jPanel_LibrosLayout);
    jPanel_LibrosLayout.setHorizontalGroup(
      jPanel_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4)
          .addGroup(jPanel_LibrosLayout.createSequentialGroup()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
            .addComponent(buttonLibrosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(buttonLibrosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel_LibrosLayout.setVerticalGroup(
      jPanel_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5)
          .addGroup(jPanel_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(buttonLibrosQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonLibrosAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel_LibrosAgregar.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_LibrosAgregar.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel6.setText("Agregar Libro");

    jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel7.setText("Titulo");

    jTextField1.setBackground(new java.awt.Color(96, 125, 139));
    jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField1.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField1.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField1.setSelectionColor(new java.awt.Color(52, 81, 94));

    jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel8.setText("Edicion");

    jTextField2.setBackground(new java.awt.Color(96, 125, 139));
    jTextField2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField2.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField2.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField2.setSelectionColor(new java.awt.Color(52, 81, 94));

    jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel9.setText("Autor");

    jTextField3.setBackground(new java.awt.Color(96, 125, 139));
    jTextField3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField3.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField3.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField3.setSelectionColor(new java.awt.Color(52, 81, 94));

    jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel10.setText("Año");

    jTextField4.setBackground(new java.awt.Color(96, 125, 139));
    jTextField4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField4.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField4.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField4.setSelectionColor(new java.awt.Color(52, 81, 94));

    buttonLibrosFormularioAgregar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonLibrosFormularioAgregar.setText("Agregar");
    buttonLibrosFormularioAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonLibrosFormularioAgregarmouseReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel_LibrosAgregarLayout = new javax.swing.GroupLayout(jPanel_LibrosAgregar);
    jPanel_LibrosAgregar.setLayout(jPanel_LibrosAgregarLayout);
    jPanel_LibrosAgregarLayout.setHorizontalGroup(
      jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosAgregarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_LibrosAgregarLayout.createSequentialGroup()
            .addComponent(jLabel6)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel_LibrosAgregarLayout.createSequentialGroup()
            .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel_LibrosAgregarLayout.createSequentialGroup()
                .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel8)
                  .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(jPanel_LibrosAgregarLayout.createSequentialGroup()
                .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel9)
                  .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(buttonLibrosFormularioAgregar, javax.swing.GroupLayout.Alignment.TRAILING))))
            .addGap(25, 25, 25))))
    );
    jPanel_LibrosAgregarLayout.setVerticalGroup(
      jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosAgregarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel6)
        .addGap(17, 17, 17)
        .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel7)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_LibrosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(buttonLibrosFormularioAgregar)
        .addContainerGap(159, Short.MAX_VALUE))
    );

    jPanel_LibrosQuitar.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_LibrosQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jPanel_LibrosQuitar.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel1.setText("Quitar Libro");

    buttonLibrosFormularioQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonLibrosFormularioQuitar.setText("Quitar");
    buttonLibrosFormularioQuitar.setPreferredSize(new java.awt.Dimension(75, 25));
    buttonLibrosFormularioQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonLibrosFormularioQuitarmouseReleased(evt);
      }
    });

    jComboBox2.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox2.setPreferredSize(new java.awt.Dimension(380, 25));

    javax.swing.GroupLayout jPanel_LibrosQuitarLayout = new javax.swing.GroupLayout(jPanel_LibrosQuitar);
    jPanel_LibrosQuitar.setLayout(jPanel_LibrosQuitarLayout);
    jPanel_LibrosQuitarLayout.setHorizontalGroup(
      jPanel_LibrosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosQuitarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_LibrosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LibrosQuitarLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(buttonLibrosFormularioQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_LibrosQuitarLayout.createSequentialGroup()
            .addGroup(jPanel_LibrosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_LibrosQuitarLayout.setVerticalGroup(
      jPanel_LibrosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_LibrosQuitarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(13, 13, 13)
        .addComponent(buttonLibrosFormularioQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(288, Short.MAX_VALUE))
    );

    jPanel_Socios.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_Socios.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel2.setText("Socios");

    buttonSociosAgregar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosAgregar.setText("Agregar");
    buttonSociosAgregar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonSociosAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosAgregarmouseReleased(evt);
      }
    });

    buttonSociosQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosQuitar.setText("Quitar");
    buttonSociosQuitar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonSociosQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosQuitarmouseReleased(evt);
      }
    });

    buttonSociosDocentesResponsables.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosDocentesResponsables.setText("Docentes Responsables");
    buttonSociosDocentesResponsables.setPreferredSize(new java.awt.Dimension(75, 25));
    buttonSociosDocentesResponsables.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosDocentesResponsablesmouseReleased(evt);
      }
    });

    jTextField5.setBackground(new java.awt.Color(96, 125, 139));
    jTextField5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField5.setText("dni del socio...");
    jTextField5.setPreferredSize(new java.awt.Dimension(290, 20));
    jTextField5.setSelectionColor(new java.awt.Color(52, 81, 94));
    jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jTextField5mouseReleased(evt);
      }
    });

    buttonSociosBuscar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosBuscar.setText("Buscar");
    buttonSociosBuscar.setMaximumSize(new java.awt.Dimension(70, 25));
    buttonSociosBuscar.setPreferredSize(new java.awt.Dimension(70, 25));
    buttonSociosBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosBuscarmouseReleased(evt);
      }
    });

    jTextArea2.setEditable(false);
    jTextArea2.setBackground(new java.awt.Color(96, 125, 139));
    jTextArea2.setColumns(20);
    jTextArea2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextArea2.setRows(5);
    jTextArea2.setSelectionColor(new java.awt.Color(52, 81, 94));
    jScrollPane2.setViewportView(jTextArea2);

    javax.swing.GroupLayout jPanel_SociosLayout = new javax.swing.GroupLayout(jPanel_Socios);
    jPanel_Socios.setLayout(jPanel_SociosLayout);
    jPanel_SociosLayout.setHorizontalGroup(
      jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2)
          .addGroup(jPanel_SociosLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonSociosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(buttonSociosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_SociosLayout.createSequentialGroup()
            .addGroup(jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(buttonSociosDocentesResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel_SociosLayout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSociosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 2, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_SociosLayout.setVerticalGroup(
      jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(buttonSociosQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonSociosAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel_SociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonSociosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(buttonSociosDocentesResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel_SociosAgregar.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_SociosAgregar.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel11.setText("Agregar Socio");

    jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel12.setText("DNI");

    jTextField6.setBackground(new java.awt.Color(96, 125, 139));
    jTextField6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField6.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField6.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField6.setSelectionColor(new java.awt.Color(52, 81, 94));

    jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel13.setText("Nombre");

    jTextField7.setBackground(new java.awt.Color(96, 125, 139));
    jTextField7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField7.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField7.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField7.setSelectionColor(new java.awt.Color(52, 81, 94));

    jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel14.setText("Tipo");

    jLabel15.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jLabel15.setText("Carrera");

    jTextField9.setBackground(new java.awt.Color(96, 125, 139));
    jTextField9.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField9.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jTextField9.setPreferredSize(new java.awt.Dimension(300, 28));
    jTextField9.setSelectionColor(new java.awt.Color(52, 81, 94));

    buttonSociosFormularioAgregar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosFormularioAgregar.setText("Agregar");
    buttonSociosFormularioAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosFormularioAgregarmouseReleased(evt);
      }
    });

    jComboBox1.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));
    jComboBox1.setPreferredSize(new java.awt.Dimension(300, 25));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel_SociosAgregarLayout = new javax.swing.GroupLayout(jPanel_SociosAgregar);
    jPanel_SociosAgregar.setLayout(jPanel_SociosAgregarLayout);
    jPanel_SociosAgregarLayout.setHorizontalGroup(
      jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_SociosAgregarLayout.createSequentialGroup()
            .addComponent(jLabel11)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
            .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
                .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel14)
                  .addComponent(jLabel15))
                .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(buttonSociosFormularioAgregar, javax.swing.GroupLayout.Alignment.TRAILING)))
                  .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
                .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel13)
                  .addComponent(jLabel12))
                .addGap(21, 21, 21)
                .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(25, 25, 25))))
    );
    jPanel_SociosAgregarLayout.setVerticalGroup(
      jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosAgregarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel11)
        .addGap(17, 17, 17)
        .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel12)
          .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel14)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel_SociosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel15)
          .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(buttonSociosFormularioAgregar)
        .addContainerGap(162, Short.MAX_VALUE))
    );

    jPanel_SociosQuitar.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_SociosQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jPanel_SociosQuitar.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel3.setText("Quitar Socio");

    buttonSociosFormularioQuitar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonSociosFormularioQuitar.setText("Quitar");
    buttonSociosFormularioQuitar.setPreferredSize(new java.awt.Dimension(75, 25));
    buttonSociosFormularioQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonSociosFormularioQuitarmouseReleased(evt);
      }
    });

    jComboBox3.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox3.setPreferredSize(new java.awt.Dimension(380, 25));

    javax.swing.GroupLayout jPanel_SociosQuitarLayout = new javax.swing.GroupLayout(jPanel_SociosQuitar);
    jPanel_SociosQuitar.setLayout(jPanel_SociosQuitarLayout);
    jPanel_SociosQuitarLayout.setHorizontalGroup(
      jPanel_SociosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosQuitarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_SociosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SociosQuitarLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(buttonSociosFormularioQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_SociosQuitarLayout.createSequentialGroup()
            .addGroup(jPanel_SociosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_SociosQuitarLayout.setVerticalGroup(
      jPanel_SociosQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_SociosQuitarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(13, 13, 13)
        .addComponent(buttonSociosFormularioQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(288, Short.MAX_VALUE))
    );

    jPanel_Prestamos.setBackground(new java.awt.Color(142, 172, 187));

    jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel4.setText("Prestamos");

    buttonPrestamosRealizar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonPrestamosRealizar.setText("Prestar");
    buttonPrestamosRealizar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonPrestamosRealizar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonPrestamosRealizarmouseReleased(evt);
      }
    });

    buttonPrestamosBuscar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonPrestamosBuscar.setText("Buscar");
    buttonPrestamosBuscar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonPrestamosBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonPrestamosBuscarmouseReleased(evt);
      }
    });

    jComboBox4.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox4.setPreferredSize(new java.awt.Dimension(275, 25));

    buttonPrestamosCancelar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonPrestamosCancelar.setText("Devolver");
    buttonPrestamosCancelar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonPrestamosCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonPrestamosCancelarmouseReleased(evt);
      }
    });

    jTextArea3.setEditable(false);
    jTextArea3.setBackground(new java.awt.Color(96, 125, 139));
    jTextArea3.setColumns(20);
    jTextArea3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jTextArea3.setRows(5);
    jTextArea3.setSelectionColor(new java.awt.Color(52, 81, 94));
    jScrollPane1.setViewportView(jTextArea3);

    javax.swing.GroupLayout jPanel_PrestamosLayout = new javax.swing.GroupLayout(jPanel_Prestamos);
    jPanel_Prestamos.setLayout(jPanel_PrestamosLayout);
    jPanel_PrestamosLayout.setHorizontalGroup(
      jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(jPanel_PrestamosLayout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPrestamosRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(buttonPrestamosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_PrestamosLayout.createSequentialGroup()
            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
            .addComponent(buttonPrestamosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel_PrestamosLayout.setVerticalGroup(
      jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(buttonPrestamosRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonPrestamosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonPrestamosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    jPanel_PrestamosPrestar.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_PrestamosPrestar.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel16.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel16.setText("Prestar Libro");

    jComboBox5.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox5.setPreferredSize(new java.awt.Dimension(380, 25));

    jComboBox6.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox6.setPreferredSize(new java.awt.Dimension(380, 25));

    buttonPrestamosFormularioRealizar.setBackground(new java.awt.Color(96, 125, 139));
    buttonPrestamosFormularioRealizar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonPrestamosFormularioRealizar.setText("Prestar");
    buttonPrestamosFormularioRealizar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonPrestamosFormularioRealizar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonPrestamosFormularioRealizarmouseReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel_PrestamosPrestarLayout = new javax.swing.GroupLayout(jPanel_PrestamosPrestar);
    jPanel_PrestamosPrestar.setLayout(jPanel_PrestamosPrestarLayout);
    jPanel_PrestamosPrestarLayout.setHorizontalGroup(
      jPanel_PrestamosPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosPrestarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_PrestamosPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PrestamosPrestarLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(buttonPrestamosFormularioRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_PrestamosPrestarLayout.createSequentialGroup()
            .addGroup(jPanel_PrestamosPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel16)
              .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_PrestamosPrestarLayout.setVerticalGroup(
      jPanel_PrestamosPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosPrestarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel16)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(buttonPrestamosFormularioRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(254, Short.MAX_VALUE))
    );

    jPanel_PrestamosDevolver.setBackground(new java.awt.Color(142, 172, 187));
    jPanel_PrestamosDevolver.setPreferredSize(new java.awt.Dimension(400, 400));

    jLabel17.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
    jLabel17.setText("Devolver Libro");

    jComboBox7.setBackground(new java.awt.Color(96, 125, 139));
    jComboBox7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox7.setPreferredSize(new java.awt.Dimension(380, 25));

    buttonPrestamosFormularioCancelar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
    buttonPrestamosFormularioCancelar.setText("Devolver");
    buttonPrestamosFormularioCancelar.setPreferredSize(new java.awt.Dimension(80, 25));
    buttonPrestamosFormularioCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        buttonPrestamosFormularioCancelarmouseReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel_PrestamosDevolverLayout = new javax.swing.GroupLayout(jPanel_PrestamosDevolver);
    jPanel_PrestamosDevolver.setLayout(jPanel_PrestamosDevolverLayout);
    jPanel_PrestamosDevolverLayout.setHorizontalGroup(
      jPanel_PrestamosDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosDevolverLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel_PrestamosDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PrestamosDevolverLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(buttonPrestamosFormularioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel_PrestamosDevolverLayout.createSequentialGroup()
            .addGroup(jPanel_PrestamosDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel17)
              .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel_PrestamosDevolverLayout.setVerticalGroup(
      jPanel_PrestamosDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_PrestamosDevolverLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel17)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(buttonPrestamosFormularioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(290, Short.MAX_VALUE))
    );

    jLayeredPane1.setLayer(jPanel_Intro, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_Libros, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_LibrosAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_LibrosQuitar, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_Socios, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_SociosAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_SociosQuitar, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_Prestamos, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_PrestamosPrestar, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel_PrestamosDevolver, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPane1Layout.createSequentialGroup()
        .addComponent(jPanel_LibrosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_Libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_LibrosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_Socios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_SociosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_SociosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_Prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_PrestamosPrestar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_PrestamosDevolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_Intro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jLayeredPane1Layout.setVerticalGroup(
      jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel_LibrosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_Libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_LibrosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_Socios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_SociosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 11, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_SociosQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 11, Short.MAX_VALUE)))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_Prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_PrestamosPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_PrestamosDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
      .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
          .addComponent(jPanel_Intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  // Establece la visibilidad de todos los JPanel del jLayeredPane1 en false.
  public void setAllJPanelInvisible () {
    javax.swing.JPanel[] componentes = {
      jPanel_Intro,
      jPanel_Libros,
      jPanel_LibrosAgregar,
      jPanel_LibrosQuitar,
      jPanel_Socios,
      jPanel_SociosAgregar,
      jPanel_SociosQuitar,
      jPanel_Prestamos,
      jPanel_PrestamosPrestar,
      jPanel_PrestamosDevolver,
    };
  
    for (javax.swing.JPanel componente : componentes) {
      componente.setVisible(false);
    }
  }

  private void buttonLibrosAgregarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLibrosAgregarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_LibrosAgregar.setVisible(true);
  }//GEN-LAST:event_buttonLibrosAgregarmouseReleased

  private void buttonLibrosQuitarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLibrosQuitarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_LibrosQuitar.setVisible(true);
    jComboBox2.removeAllItems();
    for (Libro libro : this.biblioteca.getLibros()) {
        jComboBox2.addItem(libro.getTitulo());
    }
  }//GEN-LAST:event_buttonLibrosQuitarmouseReleased

  private void buttonMenuLibrosmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuLibrosmouseReleased
    this.setAllJPanelInvisible();
    jPanel_Libros.setVisible(true);
    String texto = "Lista de Libros: \n";
    for (Libro libro : this.biblioteca.getLibros()) {
      texto += libro.toString();

      if (libro.estaPrestado()) {
        texto += " | Prestado";
      }

      texto += "\n";
    }
    jTextArea1.setText(texto);
  }//GEN-LAST:event_buttonMenuLibrosmouseReleased

  private void buttonSociosAgregarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosAgregarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_SociosAgregar.setVisible(true);
  }//GEN-LAST:event_buttonSociosAgregarmouseReleased

  private void buttonSociosQuitarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosQuitarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_SociosQuitar.setVisible(true);
    jComboBox3.removeAllItems();
    for (Socio socio : this.biblioteca.getSocios()) {
      jComboBox3.addItem(String.valueOf(socio.getDNI()));
    }
  }//GEN-LAST:event_buttonSociosQuitarmouseReleased

  private void buttonMenuPrestamosmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuPrestamosmouseReleased
    this.setAllJPanelInvisible();
    jPanel_Prestamos.setVisible(true);
    jTextArea3.setText("Prestamos vencidos:\n\n");
    for (Prestamo prestamo : this.biblioteca.obtenerPrestamosVencidos()) {
      jTextArea3.append(prestamo.toString() + "\n");
    }
    jComboBox4.removeAllItems();
    for (Libro libro : this.biblioteca.getLibros()) {
      jComboBox4.addItem(libro.getTitulo());
    }
  }//GEN-LAST:event_buttonMenuPrestamosmouseReleased

  private void buttonMenuSociosmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuSociosmouseReleased
    this.setAllJPanelInvisible();
    jPanel_Socios.setVisible(true);
    String texto = "Lista de Socios: \n";
    for (Socio socio : this.biblioteca.getSocios()) {
      texto += socio.toString() + "\n";
    }
    jTextArea2.setText(texto);
  }//GEN-LAST:event_buttonMenuSociosmouseReleased

  private void buttonPrestamosRealizarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrestamosRealizarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_PrestamosPrestar.setVisible(true);
    jComboBox5.removeAllItems();
    for (Socio socio : this.biblioteca.getSocios()) {
      jComboBox5.addItem(String.valueOf(socio.getDNI()));
    }
    jComboBox6.removeAllItems();
    for (Libro libro : this.biblioteca.getLibros()) {
        jComboBox6.addItem(libro.getTitulo());
    }
  }//GEN-LAST:event_buttonPrestamosRealizarmouseReleased

  private void buttonPrestamosCancelarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrestamosCancelarmouseReleased
    this.setAllJPanelInvisible();
    jPanel_PrestamosDevolver.setVisible(true);
    jComboBox7.removeAllItems();
    for (Libro libro : this.biblioteca.getLibros()) {
      jComboBox7.addItem(libro.getTitulo());
    }
  }//GEN-LAST:event_buttonPrestamosCancelarmouseReleased

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    if (jComboBox1.getSelectedIndex() == 0) {
      jLabel15.setText("Carrera");
    } else  {
      jLabel15.setText("Area     ");
    }
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void buttonLibrosFormularioAgregarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLibrosFormularioAgregarmouseReleased
    try{
      this.biblioteca.agregarLibro(
        jTextField1.getText(),
        Integer.valueOf(jTextField2.getText()),
        jTextField3.getText(),
        Integer.valueOf(jTextField4.getText())
      );
          
      // vaciamos
      jTextField1.setText("");
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField4.setText("");

      // mensaje
      javax.swing.JOptionPane.showMessageDialog(null, "Se ha agregado el libro exitosamente.",
        "Informacion", javax.swing.JOptionPane.PLAIN_MESSAGE);
    } catch (NumberFormatException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Algun dato no corresponde al tipo requerido.",
        "Error al agregar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonLibrosFormularioAgregarmouseReleased

  private void buttonLibrosFormularioQuitarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLibrosFormularioQuitarmouseReleased
    try {
      String tituloBuscado = jComboBox2.getSelectedItem().toString();
      Libro buscado = new Libro ("", 0, "", 0);
      for (Libro libro : this.biblioteca.getLibros()) {
        if (tituloBuscado.equals(libro.getTitulo())) {
          buscado = libro;
        }
      }
      this.biblioteca.quitarLibro(buscado);
      this.buttonLibrosQuitarmouseReleased(evt);
    } catch (NullPointerException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un libro.",
        "Error al quitar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonLibrosFormularioQuitarmouseReleased

  private void buttonSociosBuscarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosBuscarmouseReleased
    try {
      Socio buscado = this.biblioteca.buscarSocio(Integer.valueOf(jTextField5.getText()));
      if (buscado != null) {
        jTextArea2.setText(buscado.toString());
      } else {
        jTextArea2.setText("No encontrado.");
      }
      jTextField5.setText("");
    } catch (NumberFormatException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "El DNI ingresado no es valido.",
        "Error al buscar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonSociosBuscarmouseReleased

  private void buttonSociosDocentesResponsablesmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosDocentesResponsablesmouseReleased
    String texto = "Lista de Docentes Responsables: \n";
    for (Docente docente: this.biblioteca.obtenerDocentesResponsables()) {
      texto += docente.toString() + "\n";
    }
    jTextArea2.setText(texto);
  }//GEN-LAST:event_buttonSociosDocentesResponsablesmouseReleased

  private void jTextField5mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5mouseReleased
    jTextField5.setText("");
  }//GEN-LAST:event_jTextField5mouseReleased

  private void buttonSociosFormularioAgregarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosFormularioAgregarmouseReleased
    try{
      if (jComboBox1.getSelectedIndex() == 0) {
        this.biblioteca.agregarSocioEstudiante(
          Integer.valueOf(jTextField6.getText()),
          jTextField7.getText(),
          jTextField9.getText()
        );
      } else {
        this.biblioteca.agregarSocioDocente(
          Integer.valueOf(jTextField6.getText()),
          jTextField7.getText(),
          jTextField9.getText()
        );
      }
      jTextField6.setText("");
      jTextField7.setText("");
      jTextField9.setText("");

      javax.swing.JOptionPane.showMessageDialog(null, "Se ha agregado el socio exitosamente.",
        "Informacion", javax.swing.JOptionPane.PLAIN_MESSAGE);
    } catch (NumberFormatException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Algun dato no corresponde al tipo requerido.",
        "Error al agregar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonSociosFormularioAgregarmouseReleased

  private void buttonSociosFormularioQuitarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSociosFormularioQuitarmouseReleased
    try {
      int dni = Integer.valueOf(jComboBox3.getSelectedItem().toString());
      Socio buscado = null;
      for (Socio socio : this.biblioteca.getSocios()) {
        if (dni == socio.getDNI()) {
          buscado = socio;
        }
      }
      this.biblioteca.quitarSocio(buscado);
      this.buttonSociosQuitarmouseReleased(evt);
    } catch (NullPointerException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un socio.",
        "Error al quitar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonSociosFormularioQuitarmouseReleased

  private void buttonPrestamosBuscarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrestamosBuscarmouseReleased
    try {
      String tituloBuscado = jComboBox4.getSelectedItem().toString();
      Libro buscado = new Libro ("", 0, "", 0);
      for (Libro libro : this.biblioteca.getLibros()) {
        if (tituloBuscado.equals(libro.getTitulo())) {
          buscado = libro;
        }
      }
      Socio poseedor = this.biblioteca.buscarQuienTieneElLibro(buscado);
      String message;
      if (poseedor == null) {
        message = "El libro se encuentra en la biblioteca";
      } else {
        message = poseedor.getNombre();
      }
      javax.swing.JOptionPane.showMessageDialog(null, message,
        "Quien tiene el Libro", javax.swing.JOptionPane.PLAIN_MESSAGE);
    } catch (NullPointerException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un libro.",
        "Error al quitar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonPrestamosBuscarmouseReleased

  private void buttonPrestamosFormularioRealizarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrestamosFormularioRealizarmouseReleased
    try {
      String tituloBuscado = jComboBox6.getSelectedItem().toString();
      Libro libroBuscado = new Libro ("", 0, "", 0);
      for (Libro libro : this.biblioteca.getLibros()) {
        if (tituloBuscado.equals(libro.getTitulo())) {
          libroBuscado = libro;
        }
      }
      
      int dni = Integer.valueOf(jComboBox5.getSelectedItem().toString());
      Socio socioBuscado = null;
      for (Socio socio : this.biblioteca.getSocios()) {
        if (dni == socio.getDNI()) {
          socioBuscado = socio;
        }
      }
      
      if (this.biblioteca.realizarPrestamo(Calendar.getInstance(), socioBuscado, libroBuscado)) {
        javax.swing.JOptionPane.showMessageDialog(null, "Se ha realizado el prestamo con exito.",
          "Informacion", javax.swing.JOptionPane.PLAIN_MESSAGE);
      } else if (!socioBuscado.puedePedir()) {
        javax.swing.JOptionPane.showMessageDialog(null, "El socio no puede pedir prestamos.",
          "Error al prestar", javax.swing.JOptionPane.ERROR_MESSAGE);
      } else {
        javax.swing.JOptionPane.showMessageDialog(null, "El libro se encuentra prestado.",
          "Error al prestar", javax.swing.JOptionPane.ERROR_MESSAGE);
      }
    } catch (NullPointerException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un libro y un socio.",
        "Error al prestar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonPrestamosFormularioRealizarmouseReleased

  private void buttonPrestamosFormularioCancelarmouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrestamosFormularioCancelarmouseReleased
    try {
      String tituloBuscado = jComboBox7.getSelectedItem().toString();
      Libro libroBuscado = new Libro ("", 0, "", 0);
      for (Libro libro : this.biblioteca.getLibros()) {
        if (tituloBuscado.equals(libro.getTitulo())) {
          libroBuscado = libro;
        }
      }
      
      this.biblioteca.cancelarPrestamo(libroBuscado);
      javax.swing.JOptionPane.showMessageDialog(null, "El libro ha sido devuelto.",
        "Informacion", javax.swing.JOptionPane.PLAIN_MESSAGE);
    } catch (NullPointerException e) {
      javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un libro.",
        "Error al prestar", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_buttonPrestamosFormularioCancelarmouseReleased

  /**
    * @param args the command line arguments
    */
  public static void main(String args[]) {
    Biblioteca biblioteca = new Biblioteca ("LibroTeca");
      
    biblioteca.agregarLibro("El Principito", 1, "Antoine de Saint-Exupery", 1943);
    biblioteca.agregarLibro("Metamorfosis", 3, "Franz Kafka", 1915);
    biblioteca.agregarLibro("Orgullo y Prejuicio", 2, "Jane Austen", 1813);
    biblioteca.agregarLibro("Don Quijote de la Mancha", 10, "Miguel de Cervantes Saavedra", 1605);
    biblioteca.agregarLibro("Romeo y Julieta", 5, "William Shakespeare", 1597);
    biblioteca.agregarLibro("Cumbres Borrascosas", 2, "Emily Bronte", 1847);
    biblioteca.agregarLibro("El Retrato de Dorian Gray", 5, "Oscar Wilde", 1890);
    biblioteca.agregarLibro("Dracula", 8, "Bram Stoker", 1897);
    biblioteca.agregarLibro("Los Miserables", 1, "Victor Hugo", 1862);
    biblioteca.agregarLibro("Fahrenheit 451", 2, "Ray Bradbury", 1953);
    biblioteca.agregarLibro("1984", 4, "George Orwell", 1949);

    biblioteca.agregarSocioDocente(12345, "Jorge Alegre", "Matematica");
    biblioteca.agregarSocioDocente(23456, "Margarita Valero", "Matematica");
    biblioteca.agregarSocioDocente(34567, "Juan Carlos Farcas", "Informatica");
    biblioteca.agregarSocioDocente(45678, "Gaston Kohn", "Informatica");
    biblioteca.agregarSocioDocente(56789, "Guadalupe Lemos", "Fisica");
    
    Calendar fechasVencida = Calendar.getInstance();
    fechasVencida.set(2018, 9, 29);
    
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(12345), biblioteca.getLibros().get(0));
    biblioteca.realizarPrestamo(fechasVencida, biblioteca.buscarSocio(12345), biblioteca.getLibros().get(1));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(23456), biblioteca.getLibros().get(2));
    biblioteca.realizarPrestamo(fechasVencida, biblioteca.buscarSocio(34567), biblioteca.getLibros().get(3));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(45678), biblioteca.getLibros().get(4));
    biblioteca.realizarPrestamo(fechasVencida, biblioteca.buscarSocio(45678), biblioteca.getLibros().get(5));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(56789), biblioteca.getLibros().get(6));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(56789), biblioteca.getLibros().get(7));
    
    biblioteca.agregarSocioEstudiante(98765, "Laura Yoma", "Lic. en Sistemas");
    biblioteca.agregarSocioEstudiante(87654, "Marcelo Weich", "Ingenieria Electrica");
    biblioteca.agregarSocioEstudiante(76543, "Rocio Torres", "Bioquimica");
    biblioteca.agregarSocioEstudiante(65432, "Alberto Sanabria", "Lic. en Sistemas");
    biblioteca.agregarSocioEstudiante(54321, "Pablo Donati", "Prof. en Estadistica");
    
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(98765), biblioteca.getLibros().get(8));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(98765), biblioteca.getLibros().get(9));
    biblioteca.realizarPrestamo(Calendar.getInstance(), biblioteca.buscarSocio(98765), biblioteca.getLibros().get(10));

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI(biblioteca).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonLibrosAgregar;
  private javax.swing.JButton buttonSociosQuitar;
  private javax.swing.JButton buttonSociosDocentesResponsables;
  private javax.swing.JButton buttonSociosBuscar;
  private javax.swing.JButton buttonSociosFormularioAgregar;
  private javax.swing.JButton buttonSociosFormularioQuitar;
  private javax.swing.JButton buttonPrestamosRealizar;
  private javax.swing.JButton buttonPrestamosBuscar;
  private javax.swing.JButton buttonPrestamosCancelar;
  private javax.swing.JButton buttonPrestamosFormularioRealizar;
  private javax.swing.JButton buttonPrestamosFormularioCancelar;
  private javax.swing.JButton buttonLibrosQuitar;
  private javax.swing.JButton buttonMenuPrestamos;
  private javax.swing.JButton buttonMenuSocios;
  private javax.swing.JButton buttonMenuLibros;
  private javax.swing.JButton buttonLibrosFormularioAgregar;
  private javax.swing.JButton buttonLibrosFormularioQuitar;
  private javax.swing.JButton buttonSociosAgregar;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JComboBox<String> jComboBox4;
  private javax.swing.JComboBox<String> jComboBox5;
  private javax.swing.JComboBox<String> jComboBox6;
  private javax.swing.JComboBox<String> jComboBox7;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JPanel jPanel_Intro;
  private javax.swing.JPanel jPanel_Libros;
  private javax.swing.JPanel jPanel_LibrosAgregar;
  private javax.swing.JPanel jPanel_LibrosQuitar;
  private javax.swing.JPanel jPanel_Menu;
  private javax.swing.JPanel jPanel_Prestamos;
  private javax.swing.JPanel jPanel_PrestamosDevolver;
  private javax.swing.JPanel jPanel_PrestamosPrestar;
  private javax.swing.JPanel jPanel_Socios;
  private javax.swing.JPanel jPanel_SociosAgregar;
  private javax.swing.JPanel jPanel_SociosQuitar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  private javax.swing.JTextArea jTextArea3;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField9;
  // End of variables declaration//GEN-END:variables
}
